drop table if exists PUBLIC.USR cascade;

create table if not exists PUBLIC.USR
(
    USER_ID      BIGINT       generated by default as identity (start with 1),
    NICK_NAME    VARCHAR(255) not null,
    LAST_NAME    VARCHAR(255),
    FIRST_NAME   VARCHAR(255),
    PASSWORD     VARCHAR(255) not null,
    EMAIL        VARCHAR(255) not null,
    BIRTHDAY     TIMESTAMP    not null,
    PHONE_NUMBER VARCHAR(255) not null,
    ROLE_NAME    VARCHAR(255) not null,
    ENTRY_DATE   TIMESTAMP,
    UPDATE_DATE  TIMESTAMP
);

